export type LegalPage = { slug: string; title: string; summary: string; sections: { heading: string; paragraphs: string[] }[] };

const contact = "concierge@kalethon.com";
export const legalPages: LegalPage[] = [
  { slug: "privacy-policy", title: "Privacy policy", summary: "How Kalëthon uses personal information under the UK GDPR and Data Protection Act 2018.", sections: [
    { heading: "Who controls your information", paragraphs: [`Kalëthon is the controller for personal information collected through kalethon.com. Contact ${contact} for privacy questions or rights requests. The operator's legal entity name and full geographic trading address are required business details and must be published without delay.`] },
    { heading: "What we collect", paragraphs: ["We may collect identity and contact details, delivery and billing information, order and customisation specifications, customer-service messages, consent records, device/security data, and measurements you choose to provide.", "Payment card details are collected and processed by Stripe; Kalëthon does not receive the full card number. Virtual try-on portraits are processed only to create the requested preview and are not intended for marketing use."] },
    { heading: "Why we use it", paragraphs: ["We process orders, payments, delivery, returns and customer support because this is necessary to perform our contract with you. We use limited security and fraud-prevention data for legitimate interests and legal compliance. Optional marketing and non-essential tracking rely on consent where required."] },
    { heading: "Contact and marketing choices", paragraphs: [`Marketing contact is optional and unticked by default. If you opt in, we record the choice and may send occasional brand or product news. Every marketing message must offer a simple unsubscribe route; you can also withdraw consent at any time by emailing ${contact}. Withdrawing marketing consent does not affect service messages about an order.`] },
    { heading: "Sharing, transfers and retention", paragraphs: ["Information is shared only with service providers needed to operate the store, including Stripe, delivery providers, hosting, customer support and the virtual try-on processor. Providers must use it only for the agreed service.", "Where a provider processes information outside the UK, Kalëthon will use an approved transfer mechanism where required. Order and tax records may be retained for up to seven years; support records normally for two years; measurement profiles until deletion or account closure; consent evidence while relied upon; session-only try-on data only for the session unless you expressly choose otherwise."] },
    { heading: "Your rights", paragraphs: [`Depending on the lawful basis, you may request access, correction, erasure, restriction, portability or object to processing. You may withdraw consent at any time without affecting earlier lawful processing. Email ${contact}; identity verification may be required. You may complain to the UK Information Commissioner's Office.`] },
  ]},
  { slug: "cookie-policy", title: "Cookie policy", summary: "What storage technologies may be used and how to change your choices.", sections: [
    { heading: "Current position", paragraphs: ["The site uses strictly necessary browser storage to remember cookie preferences and support secure site functions. No optional analytics or advertising tracker is currently installed."] },
    { heading: "Categories", paragraphs: ["Essential: security, checkout, load balancing and remembering consent choices. Analytics: aggregated site-performance and usage measurement. Marketing: campaign attribution, advertising measurement and personalisation. Analytics and marketing remain off unless you actively allow them."] },
    { heading: "Control and duration", paragraphs: ["Use Cookie settings in the footer to accept, reject or change optional categories at any time. The preference record includes category choices, policy version and date; it may be refreshed when the policy changes. Browser controls can also delete site storage, which will cause the banner to reappear."] },
  ]},
  { slug: "terms-and-conditions", title: "Terms and conditions", summary: "The terms that apply when you browse, customise and order Kalëthon clothing.", sections: [
    { heading: "About these terms", paragraphs: [`These terms apply to purchases from Kalëthon. Contact ${contact}. The operator's legal name, geographic address, company number and VAT number (if applicable) are required business details and must be published without delay. Nothing here limits mandatory consumer rights.`] },
    { heading: "Products and customisation", paragraphs: ["Images and digital previews show style and approximate colour; screens and production materials vary. Check every colour, size, fit, sleeve, trim and branding choice before payment. Virtual try-on is illustrative and does not guarantee fit.", "An order is accepted when Kalëthon sends confirmation. If a material, price or availability error prevents fulfilment, we will contact you and refund amounts paid for the affected item."] },
    { heading: "Prices and payment", paragraphs: ["Prices are shown in GBP and include applicable UK taxes unless stated otherwise. Delivery charges are displayed before payment. Stripe processes payment securely; orders may be subject to fraud and authorisation checks."] },
    { heading: "Made-to-order cancellation", paragraphs: ["The statutory change-of-mind cancellation right may not apply to goods made to your specifications or clearly personalised. This does not affect rights where goods are faulty, not as described or otherwise fail mandatory standards. Production timing and any cancellation window before cutting begins will be shown in the order confirmation."] },
    { heading: "Liability and law", paragraphs: ["Kalëthon does not exclude liability that cannot lawfully be excluded, including for death or personal injury caused by negligence, fraud, or mandatory consumer rights. These terms are governed by the laws applicable in England and Wales, without depriving consumers of mandatory protections in their home jurisdiction."] },
  ]},
  { slug: "delivery", title: "Delivery policy", summary: "Production, dispatch, tracking, customs and delivery responsibilities.", sections: [
    { heading: "Made-to-order lead times", paragraphs: ["The estimated production and delivery window is shown at checkout or in order confirmation. Unless another time is agreed, UK consumer orders will be delivered without undue delay and normally within 30 days. If a delay changes the agreed date, Kalëthon will contact you with options."] },
    { heading: "Charges and tracking", paragraphs: ["Available services, destination limits and charges are shown before payment. Tracking is sent when available. International customers are responsible for import duties and taxes unless checkout expressly states they are included."] },
    { heading: "Risk and failed delivery", paragraphs: ["Goods remain Kalëthon's responsibility until delivered to you or a person you identify, except where you independently appoint a carrier not offered by us. Report loss, damage or an incorrect item promptly to concierge@kalethon.com with the order number and photographs where relevant."] },
  ]},
  { slug: "returns-and-refunds", title: "Returns and refunds", summary: "Change-of-mind, personalised-item and faulty-goods routes.", sections: [
    { heading: "Standard, non-personalised items", paragraphs: ["For eligible online purchases, tell us within 14 days after delivery that you wish to cancel, then return the item within the following 14 days. Items may be inspected as they would be in a shop; a deduction may apply for handling beyond that. Standard outbound delivery is refunded where legally required."] },
    { heading: "Custom and personalised items", paragraphs: ["Goods made to your measurements, selected specifications or clear personalisation are generally excluded from the statutory change-of-mind cancellation right. We may still offer a discretionary alteration or return where stated in the product or order confirmation."] },
    { heading: "Faulty or incorrect goods", paragraphs: ["Personalisation never removes statutory quality rights. Contact concierge@kalethon.com if an item is faulty, not as described or incorrect. UK consumers may have a short-term right to reject within 30 days and later rights to repair or replacement. Approved refunds are made to the original payment method without undue delay and in line with legal time limits."] },
    { heading: "Starting a return", paragraphs: ["Email the order number, item, reason and photographs if relevant. Do not send made-to-order goods before receiving return instructions. A geographic returns address and any applicable consumer cancellation form must be published without delay."] },
  ]},
  { slug: "accessibility", title: "Accessibility statement", summary: "Kalëthon's commitment to an inclusive shopping and customisation experience.", sections: [
    { heading: "Our approach", paragraphs: ["We aim for keyboard access, readable contrast, clear focus states, labelled controls, reduced-motion support and responsive layouts. We test essential shopping, customisation and legal-information paths."] },
    { heading: "Help and feedback", paragraphs: [`If a page, size chart or customisation control is difficult to use, email ${contact} with the page and assistance needed. We will offer the information or service in a reasonable alternative format.`] },
  ]},
  { slug: "virtual-try-on-privacy", title: "Virtual try-on privacy", summary: "Special information for portrait processing and AI-generated clothing previews.", sections: [
    { heading: "Your choice", paragraphs: ["Virtual try-on is optional and is not required to purchase. Only upload a photograph of yourself, or one you have authority to use. Do not upload photographs of children."] },
    { heading: "Processing and limits", paragraphs: ["A portrait and selected garment image are sent to the configured try-on processor solely to generate the requested preview. Kalëthon does not use portraits to train marketing models or identify you. The output is a style visualisation, not a biometric identity check or guarantee of fit, colour or drape."] },
    { heading: "Retention and deletion", paragraphs: [`The current Kalëthon flow does not intentionally store the portrait or generated result after processing. Processor-side retention must be confirmed contractually before public launch. Contact ${contact} with privacy concerns.`] },
  ]},
];

export function getLegalPage(slug: string) { return legalPages.find((page) => page.slug === slug); }
